### ISSUE TITLE
Roassal crashes after installation

### ISSUE THREAD

**Issue by olekscode** [ObjectProfile/Roassal2#9] opened 2018-09-18 18:00 UTC
I'm trying to do something with Roassal, and it just crashes my image.
Here are the steps of what I did:

1. Installed a fresh Pharo 6.1 64-bit image using Pharo Launcher on Mac
2. Installed Roassal2 using the Metacello script from Roassal's GitHub: https://github.com/ObjectProfile/Roassal2#pharo
3. Opened World Menu > Roassal > Roassal examples > Geographical maps 

On the last step, my image crashes.

**Comment by bergel** [comment] 2018-09-23 01:35
Oleks, I am not able to reproduce your issue. Have you tried to remove the `~/Documents/Pharo/vms` folder and open again the Pharo 6.1 image? Make sure you have a recent version of the Pharo launcher.

I close the issue for now, since I cannot reproduce it. Let us know how it goes.

**Closed as completed by bergel** 2018-09-23 01:35 UTC
